In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
# Reading Excel sheets
EvanMiya = pd.read_excel("EvanMiya.xlsx")
HDI = pd.read_excel("HDI 23-24.xlsx")

# Extracting unique team names from EvanMiya and HDI datasets
evanmiya_teams = set(EvanMiya['Team'].unique())
hdi_teams = set(HDI['Team'].unique())

# Finding differences in team names between the datasets
team_name_differences = evanmiya_teams.symmetric_difference(hdi_teams)

# Outputting the number of differences in team names
num_differences = len(team_name_differences)
print(f"Number of differences in team names: {num_differences}")

print("Team names spelled differently:")
for team_name in team_name_differences:
    print(team_name)

Number of differences in team names: 126
Team names spelled differently:
Miami (FL)
Southeastern Louisiana
USC
Loyola Marymount
SFA
Louisiana-Monroe
Col. of Charleston
Florida Atlantic
Southern Mississippi
Western Caro.
McNeese
UNI
Miami (Ohio)
Lamar
Northern Ariz.
Cal State Bakersfield
South Carolina Upstate
Southern Illinois
Appalachian State
Saint Thomas (MN)
Eastern Ill.
SIUE
Central Conn. State
Boston University
ULM
Ark.-Pine Bluff
Eastern Washington
ETSU
Northern Colo.
College of Charleston
Middle Tennessee
Central Mich.
Western Ill.
Purdue Fort Wayne
Incarnate Word
Fort Wayne
Alcorn
Southeast Mo. State
North Carolina A&T
LMU (CA)
FDU
Army West Point
Stephen F. Austin
Long Island
UNCW
Northern Kentucky
CSUN
Mount St. Mary's
Texas A&M-Commerce
Northern Illinois
Central Connecticut
Army
Southern Ill.
App State
McNeese State
Saint Mary's
South Fla.
Charleston Southern
North Carolina Central
Saint Mary's (CA)
Eastern Mich.
USC Up State
UIW
Alcorn State
NIU
Mount State Mary's
Tex. A&M-Commerce
Northern Iowa
Fla. Atlantic
South Florida
Miami (Fla.)
Sam Houston
Southern U.
Southern California
Ga. Southern
Southern
UT Martin
Lamar University
Eastern Michigan
Georgia Southern
Eastern Wash.
East Tennessee State
Texas-Rio Grande Valley
N.C. Central
Missouri-Kansas City
Northern Arizona
Tennessee-Martin
Miami (OH)
UConn
Fairleigh Dickinson
Cal State Northridge
Sam Houston State
SIU Edwardsville
Western Illinois
Queens
UMES
Western Michigan
Charleston So.
Southeastern La.
Western Carolina
UTRGV
Mississippi Val.
Northern Ky.
FGCU
CSU Bakersfield
Boston U.
Saint Thomas (Minn.)
Maryland-Eastern Shore
Southern Miss.
Northern Colorado
Western Mich.
Mississippi Valley State
Seattle
UNC Wilmington
Central Michigan
Queens (NC)
LIU
Florida Gulf Coast
Eastern Illinois
Seattle U
Kansas City
Connecticut
Middle Tenn.
N.C. A&T
Southeast Missouri State
Arkansas-Pine Bluff

In [7]:
# Reading HDI dataset
HDI = pd.read_excel("HDI 23-24.xlsx")

# Combining first name and last name columns
HDI['Full Name'] = HDI['First Name'] + ' ' + HDI['Last Name']

# Finding duplicate names in the 'Full Name' column
duplicate_names = HDI[HDI.duplicated(subset='Full Name', keep=False)]['Full Name'].unique()

# Displaying duplicate names
print("Duplicate names in HDI data:")
for name in duplicate_names:
    print(name)

Duplicate names in HDI data:
David Jones
Isaac Jones
Justin Moore
Isaiah Crawford
Xavier Johnson
Kobe Johnson
Jalen Thomas
Jalen Jackson
Cameron Brown
Caleb Fields
Isaiah Thompson
Brian Taylor
Josh Smith
AJ Smith
Tyler Harris
Justin Taylor
Jordan Johnson
Joshua Hughes
Trey Thomas
RJ Johnson
Elijah Jones
Josiah Harris
Austin Williams
Bryce Johnson
Anthony Robinson
Jaden Daughtry
Isaiah Griffin
Jordan Crawford
Curtis Williams
Nathan Johnson
Chauncey Gibson
Jalen White
Mason Jones
Chase Martin
Jalen Brown
Jordan Williams
Christian Moore
Chris Morgan
Marko Sarenac
Jamel Melvin
Braylon Jackson
Zach Hayn
Jackson Prince
Jacob Morales

In [8]:
# Reading EvanMiya dataset
EvanMiya = pd.read_excel("EvanMiya.xlsx")

# Finding duplicate names in the 'Name' column
duplicate_names = EvanMiya[EvanMiya.duplicated(subset='Name', keep=False)]['Name'].unique()

# Displaying duplicate names
print("Duplicate names in EvanMiya data:")
for name in duplicate_names:
    print(name)

Duplicate names in EvanMiya data:
Xavier Johnson
Kobe Johnson
David Jones
Isaac Jones
Justin Moore
Jalen Thomas
Nendah Tarke
Cameron Brown
Justin Taylor
Caleb Fields
Josiah Harris
Jalen Jackson
Isaiah Thompson
Austin Williams
Josh Smith
Joshua Hughes
Tyler Harris
N'famara Dabo
Brian Taylor
Christian Jones
Chris Morgan
Jordan Crawford
Bryce Johnson
Jaden Daughtry
Jordan Williams
AJ Smith
Christian Moore
Curtis Williams
Jackson Prince
Elijah Jones
Mason Jones
Marko Sarenac
RJ Johnson
Jordan Johnson
Jalen White
Jalen Brown
Isaiah Griffin
Chase Martin
Braylon Jackson

In [12]:
# Reading EvanMiya dataset
EvanMiya = pd.read_excel("EvanMiya.xlsx")

# Counting duplicate player names
num_duplicates = EvanMiya.duplicated(subset='Name').sum()

# Outputting the count of duplicate player names
print(f"Number of duplicate player names in EvanMiya data: {num_duplicates}")

Number of duplicate player names in EvanMiya data: 41

In [13]:
# Reading Excel sheets
EvanMiya = pd.read_excel("EvanMiya.xlsx")
HDI = pd.read_excel("Transfer Project Data 24.xlsx")

# Extracting unique team names from EvanMiya and HDI datasets
evanmiya_teams = set(EvanMiya['Team'].unique())
hdi_teams = set(HDI['School'].unique())

# Finding differences in team names between the datasets
team_name_differences = evanmiya_teams.symmetric_difference(hdi_teams)

# Outputting the number of differences in team names
num_differences = len(team_name_differences)
print(f"Number of differences in team names: {num_differences}")

print("Team names spelled differently:")
for team_name in team_name_differences:
    print(team_name)

Number of differences in team names: 64
Team names spelled differently:
Southern Methodist
VCU
SMU
Albany
Brigham Young
Virginia Commonwealth
UMBC
Detroit Mercy
Saint John's
Little Rock
Louisiana
Miami (FL)
Loyola (IL)
LSU
USC
Albany (NY)
Miami (Ohio)
Saint Bonaventure
Ole Miss
Nevada-Las Vegas
Purdue Fort Wayne
St. Bonaventure
Arkansas-Little Rock
Massachusetts-Lowell
Fort Wayne
Maryland-Baltimore County
Mississippi
FDU
Long Island
Virginia Military Institute
Loyola (MD)
Central Connecticut
Bowling Green
Saint Mary's
UMass Lowell
Saint Mary's (CA)
Detroit
Bowling Green State
Miami (Fla.)
Sam Houston
UNLV
Southern California
Loyola Maryland
Southern Illinois-Edwardsville
BYU
Loyola Chicago
Missouri-Kansas City
Miami (OH)
Long Island University
Fairleigh Dickinson
Sam Houston State
SIU Edwardsville
Queens
Central Connecticut State
Louisiana State
St. John's (NY)
Saint Thomas (Minn.)
St. Thomas
Penn
Louisiana-Lafayette
Queens (NC)
Kansas City
Pennsylvania
VMI

In [17]:
data_18_23 = pd.read_excel("Transfer Project Data 18-23.xlsx")
data_24 = pd.read_excel("Transfer Project Data 24.xlsx")

print(type(data_18_23))
print(type(data_24))

combined_data = pd.concat([data_18_23, data_24], ignore_index=True)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [19]:
combined_data

,Player,Class,Pos,School,Conf,G,MP,tRB,tAST,tSTL,...,TRBp,ASTp,STLp,BLKp,PER,WS,BPM,Year,cSRS,cSOS
0,Jonathan Noel,SR,C,Boston College,Atlantic Coast Conference,1,1,0,0,0,...,0.0,0.0,0.0,0.0,165.8,0.1,236.8,22-23,7.47,5.63
1,Amar Ross,SR,G,Southern California,Pac-12 Conference,1,1,2,0,0,...,2.0,0.0,0.0,0.0,199.1,0.1,139.1,21-22,9.49,7.35
2,Justin Rumph,JR,G,Mississippi State,Southeastern Conference,1,1,1,0,0,...,1.0,0.0,0.0,0.0,188.3,0.1,121.5,20-21,11.18,8.48
3,Sullivan Kulju,SR,F,Richmond,Atlantic 10 Conference,2,9,0,1,2,...,0.0,0.5,1.0,0.0,31.6,0.1,110.0,20-21,3.54,3.10
4,Trace Arbuckle,JR,G,Vanderbilt,Southeastern Conference,1,1,0,0,0,...,0.0,0.0,0.0,0.0,167.5,0.1,106.0,19-20,10.76,7.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29832,Miles Webb,SO,F,Saint Francis (PA),Northeast Conference,30,380,78,16,6,...,2.6,0.5,0.2,0.3,10.2,0.4,-7.2,23-24,-12.70,-8.48
29833,Eli Wilborn,FR,F,Saint Francis (PA),Northeast Conference,30,768,222,52,25,...,7.4,1.7,0.8,1.6,22.3,2.5,-1.7,23-24,-12.70,-8.48
29834,Zaire Williams,JR,G,Wagner,Northeast Conference,9,221,19,11,12,...,2.1,1.2,1.3,0.0,12.7,0.6,0.4,23-24,-12.70,-8.48
29835,Maxwell Zegarowski,SR,F,Stonehill,Northeast Conference,30,1037,144,55,13,...,4.8,1.8,0.4,0.3,13.6,1.8,-3.6,23-24,-12.70,-8.48
29836,Seck Zongo,FR,F,Wagner,Northeast Conference,27,430,95,16,16,...,3.5,0.6,0.6,0.2,12.2,1.3,-4.5,23-24,-12.70,-8.48